
name: planetapp
description: "A new Flutter project."
# 이 설정은 pub.dev에 공개하지 않도록 설정하는 옵션입니다.
publish_to: 'none' 

# 앱 버전 및 빌드 번호
version: 1.0.0+1

environment:
  sdk: ^3.8.1 # Dart SDK 최소 버전

dependencies:
  flutter:
    sdk: flutter

  # table_calendar 패키지 설치 (캘린더)
  table_calendar: ^3.0.7

  # Firebase 코어 패키지
  firebase_core: ^3.15.1

  # Firebase 푸시 알림
  firebase_messaging: ^15.2.9

  # Firebase 인증 
  firebase_auth: ^5.6.2

  # Firestore 데이터베이스
  cloud_firestore: ^5.6.11

  # mailer 패키지 추가 (Gmail SMTP)
  mailer: ^6.5.0

  # 로컬 알림 패키지 ★
  flutter_local_notifications: ^17.2.3

  # 알람 정확히 한국시간(KST) 맞추기
  timezone: ^0.9.2

  # iOS 스타일 아이콘 패키지
  cupertino_icons: ^1.0.8

  # 날짜 포맷팅용 패키지
  intl: ^0.18.0
  permission_handler: ^12.0.1

  # 홈화면 종모양 알림 뱃지 표시용
  badges: ^3.0.3

  # SVG 이미지 사용을 위한 패키지
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 코드 품질 검사 린트
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # 앱에서 사용하는 이미지, 폰트 등 리소스 등록
  assets:
    - assets/app_icon/logo.svg
    - assets/app_icon/logo.png
    - assets/images/filter.png   #추가된 필터 아이콘

  # 커스텀 폰트 등록 (YClover)
  fonts:
    - family: YClover
      fonts:
        - asset: assets/fonts/YClover-Regular.ttf
          weight: 400
        - asset: assets/fonts/YClover-Bold.ttf
          weight: 700
